require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::MasterpiecesController do

  def mock_masterpiece(stubs={})
    @mock_masterpiece ||= mock_model(Admin::Masterpiece, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all admin_masterpieces as @admin_masterpieces" do
      Admin::Masterpiece.stub(:all) { [mock_masterpiece] }
      get :index
      assigns(:admin_masterpieces).should eq([mock_masterpiece])
    end
  end

  describe "GET show" do
    it "assigns the requested masterpiece as @masterpiece" do
      Admin::Masterpiece.stub(:find).with("37") { mock_masterpiece }
      get :show, :id => "37"
      assigns(:masterpiece).should be(mock_masterpiece)
    end
  end

  describe "GET new" do
    it "assigns a new masterpiece as @masterpiece" do
      Admin::Masterpiece.stub(:new) { mock_masterpiece }
      get :new
      assigns(:masterpiece).should be(mock_masterpiece)
    end
  end

  describe "GET edit" do
    it "assigns the requested masterpiece as @masterpiece" do
      Admin::Masterpiece.stub(:find).with("37") { mock_masterpiece }
      get :edit, :id => "37"
      assigns(:masterpiece).should be(mock_masterpiece)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created masterpiece as @masterpiece" do
        Admin::Masterpiece.stub(:new).with({'these' => 'params'}) { mock_masterpiece(:save => true) }
        post :create, :masterpiece => {'these' => 'params'}
        assigns(:masterpiece).should be(mock_masterpiece)
      end

      it "redirects to the created masterpiece" do
        Admin::Masterpiece.stub(:new) { mock_masterpiece(:save => true) }
        post :create, :masterpiece => {}
        response.should redirect_to(admin_masterpiece_url(mock_masterpiece))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved masterpiece as @masterpiece" do
        Admin::Masterpiece.stub(:new).with({'these' => 'params'}) { mock_masterpiece(:save => false) }
        post :create, :masterpiece => {'these' => 'params'}
        assigns(:masterpiece).should be(mock_masterpiece)
      end

      it "re-renders the 'new' template" do
        Admin::Masterpiece.stub(:new) { mock_masterpiece(:save => false) }
        post :create, :masterpiece => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested masterpiece" do
        Admin::Masterpiece.stub(:find).with("37") { mock_masterpiece }
        mock_admin_masterpiece.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :masterpiece => {'these' => 'params'}
      end

      it "assigns the requested masterpiece as @masterpiece" do
        Admin::Masterpiece.stub(:find) { mock_masterpiece(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:masterpiece).should be(mock_masterpiece)
      end

      it "redirects to the masterpiece" do
        Admin::Masterpiece.stub(:find) { mock_masterpiece(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(admin_masterpiece_url(mock_masterpiece))
      end
    end

    describe "with invalid params" do
      it "assigns the masterpiece as @masterpiece" do
        Admin::Masterpiece.stub(:find) { mock_masterpiece(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:masterpiece).should be(mock_masterpiece)
      end

      it "re-renders the 'edit' template" do
        Admin::Masterpiece.stub(:find) { mock_masterpiece(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested masterpiece" do
      Admin::Masterpiece.stub(:find).with("37") { mock_masterpiece }
      mock_admin_masterpiece.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the admin_masterpieces list" do
      Admin::Masterpiece.stub(:find) { mock_masterpiece }
      delete :destroy, :id => "1"
      response.should redirect_to(admin_masterpieces_url)
    end
  end

end
