require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CroppalsController do

  def mock_croppal(stubs={})
    @mock_croppal ||= mock_model(Croppal, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all croppals as @croppals" do
      Croppal.stub(:all) { [mock_croppal] }
      get :index
      assigns(:croppals).should eq([mock_croppal])
    end
  end

  describe "GET show" do
    it "assigns the requested croppal as @croppal" do
      Croppal.stub(:find).with("37") { mock_croppal }
      get :show, :id => "37"
      assigns(:croppal).should be(mock_croppal)
    end
  end

  describe "GET new" do
    it "assigns a new croppal as @croppal" do
      Croppal.stub(:new) { mock_croppal }
      get :new
      assigns(:croppal).should be(mock_croppal)
    end
  end

  describe "GET edit" do
    it "assigns the requested croppal as @croppal" do
      Croppal.stub(:find).with("37") { mock_croppal }
      get :edit, :id => "37"
      assigns(:croppal).should be(mock_croppal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created croppal as @croppal" do
        Croppal.stub(:new).with({'these' => 'params'}) { mock_croppal(:save => true) }
        post :create, :croppal => {'these' => 'params'}
        assigns(:croppal).should be(mock_croppal)
      end

      it "redirects to the created croppal" do
        Croppal.stub(:new) { mock_croppal(:save => true) }
        post :create, :croppal => {}
        response.should redirect_to(croppal_url(mock_croppal))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved croppal as @croppal" do
        Croppal.stub(:new).with({'these' => 'params'}) { mock_croppal(:save => false) }
        post :create, :croppal => {'these' => 'params'}
        assigns(:croppal).should be(mock_croppal)
      end

      it "re-renders the 'new' template" do
        Croppal.stub(:new) { mock_croppal(:save => false) }
        post :create, :croppal => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested croppal" do
        Croppal.stub(:find).with("37") { mock_croppal }
        mock_croppal.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :croppal => {'these' => 'params'}
      end

      it "assigns the requested croppal as @croppal" do
        Croppal.stub(:find) { mock_croppal(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:croppal).should be(mock_croppal)
      end

      it "redirects to the croppal" do
        Croppal.stub(:find) { mock_croppal(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(croppal_url(mock_croppal))
      end
    end

    describe "with invalid params" do
      it "assigns the croppal as @croppal" do
        Croppal.stub(:find) { mock_croppal(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:croppal).should be(mock_croppal)
      end

      it "re-renders the 'edit' template" do
        Croppal.stub(:find) { mock_croppal(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested croppal" do
      Croppal.stub(:find).with("37") { mock_croppal }
      mock_croppal.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the croppals list" do
      Croppal.stub(:find) { mock_croppal }
      delete :destroy, :id => "1"
      response.should redirect_to(croppals_url)
    end
  end

end
